remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

show_downloads: true
description: ""
logo: /assets/importsort-d.png
github:
  zip_url: https://github.com/friedelschoen/importsort-d/zipball/master
  tar_url: https://github.com/friedelschoen/importsort-d/tarball/master
  owner_name: Friedel Sch&ouml;n
